# Generated by Django 3.1.7 on 2021-04-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_models', '0002_remove_user_raw_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='raw_password',
            field=models.TextField(blank=True, null=True),
        ),
    ]
